server:
  port: 8081
spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/joy?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  redis:
    host: 192.168.10.128
    port: 6379
    timeout: 3000
    database: 8


#==============================knife4j配置==============================
knife4j:
  enable: true
  basic:
    enable: true
    username: test
    password: 123456
  openapi:
    title: 徐徐乐之博客接口文档
    description: 一个专注于技术分享的博客平台
    # aaa"
    email: 248954763@qq.com
    concat: 徐徐乐之
    url: https://www.lexujia.com
    version: v1.0
    group:
      test1:
        group-name: 分组名称
        api-rule: package
        api-rule-resources:
          - com.joy
