import { post, type ApiResponse, type RequestOptions } from '@/utils/request.uts';

import { LoginResult,VerifyCodeData } from '@/types/userType.uts';


// ======================== 接口函数 ========================

/** 获取邮箱验证码 */
export function fetchEmailVerifyCode(email : string, action : string) : Promise<ApiResponse<VerifyCodeData>> {
	return post<VerifyCodeData>('infra/auth/email/verifyCode', {
		email: email,
		action
	} as UTSJSONObject, {
		autoToast: false
	} as RequestOptions);
}

/** 登录 */
export function login(phone : string, password : string) : Promise<ApiResponse<LoginResult>> {
	return post<LoginResult>('infra/auth/login', {
		phone: phone,
		password: password
	} as UTSJSONObject, {
		autoToast: false
	} as RequestOptions);
}

/** 注册 */
export function register(
	phone : string,
	email : string,
	code : string,
	password : string,
	validTime : number
) : Promise<ApiResponse<LoginResult>> {
	return post<LoginResult>('infra/auth/register', {
		phone: phone,
		email: email,
		code: code,
		password: password,
		validTime: validTime
	} as UTSJSONObject, {
		autoToast: false
	} as RequestOptions);
}

/** 重置密码 */
export function resetPassword(
	email : string,
	code : string,
	newPassword : string,
	validTime : number
) : Promise<ApiResponse<null>> {
	return post<null>('infra/auth/reset/password', {
		email: email,
		code: code,
		newPassword: newPassword,
		validTime: validTime
	} as UTSJSONObject, {
		autoToast: false
	} as RequestOptions);
}

export function oneClickLogin(code : string) : Promise<ApiResponse<LoginResult>> {
	return post<LoginResult>('infra/auth/wxLogin', {
		code: code
	} as UTSJSONObject, {
		autoToast: false
	} as RequestOptions);
}

/** 微信绑定 */
export function wxBind(
	phone : string,
	email : string,
	code : string,
	validTime : number,
	wxToken : string
) : Promise<ApiResponse<LoginResult>> {
	return post<LoginResult>('infra/auth/wxBind', {
		phone: phone,
		email: email,
		code: code,
		validTime: validTime,
		wxToken: wxToken
	} as UTSJSONObject, {
		autoToast: false
	} as RequestOptions);
}